# Generated by Django 6.0 on 2026-01-05 06:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('original_hash', models.CharField(db_index=True, max_length=64)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('complaint_count', models.IntegerField(default=0)),
                ('last_submission', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complaint_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('tracking_code', models.CharField(max_length=12, unique=True)),
                ('encrypted_content', models.TextField()),
                ('severity', models.IntegerField(choices=[(1, '⚪ Low'), (2, '🟢 Medium'), (3, '🟡 High'), (4, '🔴 Critical')], default=2)),
                ('submission_date', models.DateField(auto_now_add=True)),
                ('submission_hour', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', '🟡 Pending'), ('reviewing', '🔵 Under Review'), ('resolved', '✅ Resolved'), ('escalated', '⚡ Escalated'), ('rejected', '❌ Rejected')], default='pending', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('response_deadline', models.DateField()),
                ('escalation_level', models.IntegerField(default=0)),
                ('evidence_count', models.IntegerField(default=0)),
                ('upvote_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('submitted', 'Complaint Submitted'), ('read', 'Complaint Read'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned to Staff'), ('escalated', 'Escalated'), ('commented', 'Comment Added'), ('evidence_added', 'Evidence Added')], max_length=50)),
                ('encrypted_details', models.TextField()),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_severity', models.IntegerField(default=2, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
                ('response_days', models.IntegerField(default=7)),
                ('icon', models.CharField(default='📝', max_length=50)),
                ('requires_evidence', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Complaint Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ComplaintEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_hash', models.CharField(db_index=True, max_length=64)),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(max_length=100)),
                ('file_size', models.IntegerField()),
                ('storage_path', models.TextField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Complaint Evidences',
            },
        ),
        migrations.CreateModel(
            name='ComplaintSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cooldown_hours', models.IntegerField(default=24, help_text='Hours between complaints from same user')),
                ('session_hours', models.IntegerField(default=24, help_text='Anonymous session duration')),
                ('max_complaints_per_day', models.IntegerField(default=3, help_text='Max complaints per user daily')),
                ('require_verification', models.BooleanField(default=False, help_text='Require email verification')),
                ('auto_escalate_days', models.IntegerField(default=7, help_text='Auto-escalate after X days')),
                ('notify_principal', models.BooleanField(default=True, help_text='Notify principal on new complaints')),
            ],
            options={
                'verbose_name_plural': 'Complaint Settings',
            },
        ),
    ]
