# Generated by Django 6.0 on 2026-01-05 06:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('complaints', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussession',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='anonymous_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='assigned_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='complaints.anonymoussession'),
        ),
        migrations.AddField(
            model_name='complaintaction',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='complaints.complaint'),
        ),
        migrations.AddField(
            model_name='complaintaction',
            name='member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='complaint',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='complaints.complaintcategory'),
        ),
        migrations.AddField(
            model_name='complaintevidence',
            name='complaint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidences', to='complaints.complaint'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['session_hash', 'expires_at'], name='complaints__session_b7dcb8_idx'),
        ),
        migrations.AddIndex(
            model_name='anonymoussession',
            index=models.Index(fields=['original_hash', 'created_at'], name='complaints__origina_a064b0_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['status', 'response_deadline'], name='complaints__status_b4319d_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['tracking_code'], name='complaints__trackin_513965_idx'),
        ),
        migrations.AddIndex(
            model_name='complaint',
            index=models.Index(fields=['session', 'created_at'], name='complaints__session_0a9134_idx'),
        ),
    ]
