# Generated by Django 6.0 on 2026-01-05 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintaction',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='complaintaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Complaint Submitted'), ('read', 'Complaint Read'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned to Staff'), ('escalated', 'Escalated'), ('commented', 'Comment Added'), ('evidence_added', 'Evidence Added'), ('reply', 'Principal Reply')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintaction',
            name='encrypted_details',
            field=models.TextField(blank=True),
        ),
    ]
