# Generated by Django 6.0 on 2026-01-06 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0003_complaintaction_notes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsettings',
            name='require_verification',
            field=models.BooleanField(default=False, help_text='Require manual verification before posting'),
        ),
    ]
