# Generated by Django 6.0 on 2026-01-06 10:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0004_alter_complaintsettings_require_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='ai_priority_score',
            field=models.IntegerField(default=50, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AddField(
            model_name='complaint',
            name='ai_summary',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
