# Generated by Django 6.0 on 2026-01-06 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0005_complaint_ai_priority_score_complaint_ai_summary'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='ai_priority_score',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='ai_summary',
        ),
    ]
