# Generated by Django 6.0 on 2026-01-06 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0006_remove_complaint_ai_priority_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonymoussession',
            name='hashed_ip',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
