# Generated by Django 6.0 on 2026-01-06 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0007_anonymoussession_hashed_ip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsettings',
            name='max_complaints_per_day',
            field=models.IntegerField(default=2, help_text='Max complaints per user daily'),
        ),
    ]
