# Generated by Django 6.0 on 2026-01-07 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0008_alter_complaintsettings_max_complaints_per_day'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='anonymoussession',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='anonymoussession',
            name='user_agent',
        ),
    ]
