# Generated by Django 6.0 on 2026-01-07 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0009_remove_anonymoussession_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
    ]
