# Generated by Django 6.0 on 2026-01-07 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0010_alter_complaint_options_complaint_is_edited'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Pending'), ('reviewing', '🔵 Under Review'), ('resolved', '✅ Resolved')], default='pending', max_length=20),
        ),
    ]
