# Generated by Django 6.0 on 2026-01-07 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0011_alter_complaint_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
