# Generated by Django 6.0 on 2026-01-07 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0012_complaint_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='image_attachment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
