# Generated by Django 6.0 on 2026-01-07 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0013_complaint_image_attachment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintcategory',
            name='response_days',
            field=models.IntegerField(default=10),
        ),
    ]
