# Generated by Django 6.0 on 2026-01-07 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0014_alter_complaintcategory_response_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='has_new_reply',
            field=models.BooleanField(default=False),
        ),
    ]
