# Generated by Django 6.0 on 2026-01-07 06:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0015_complaint_has_new_reply'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Complaint Submitted'), ('read', 'Complaint Read'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned to Staff'), ('escalated', 'Escalated'), ('commented', 'Comment Added'), ('evidence_added', 'Evidence Added'), ('reply', 'Principal Reply'), ('update_deadline', 'Deadline Updated')], max_length=50),
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('reply', 'New Reply'), ('status', 'Status Update'), ('deadline', 'Deadline Changed'), ('escalation', 'Escalated'), ('general', 'General Announcement')], default='general', max_length=50)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='complaints.complaint')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
