# Generated by Django 6.0 on 2026-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0016_alter_complaintaction_action_type_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsettings',
            name='global_max_daily',
            field=models.IntegerField(default=150, help_text='Max total complaints allowed per day system-wide'),
        ),
        migrations.AddField(
            model_name='complaintsettings',
            name='is_frozen',
            field=models.BooleanField(default=False, help_text='Whether the system is currently frozen for new complaints'),
        ),
    ]
