# Generated by Django 6.0 on 2026-01-24 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0017_complaintsettings_global_max_daily_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaintsettings',
            name='global_max_daily',
            field=models.IntegerField(default=200, help_text='Max total complaints allowed per day system-wide'),
        ),
    ]
