# Generated by Django 6.0 on 2026-01-24 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0018_alter_complaintsettings_global_max_daily'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsettings',
            name='enable_auto_freeze',
            field=models.BooleanField(default=True, help_text='Automatically freeze system when daily limit is reached'),
        ),
    ]
