# Generated by Django 6.0 on 2026-01-24 07:05

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0019_complaintsettings_enable_auto_freeze'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsettings',
            name='daily_limit_changes',
            field=models.IntegerField(default=0, help_text='Number of times limit was changed today'),
        ),
        migrations.AddField(
            model_name='complaintsettings',
            name='last_limit_change_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
