# Generated by Django 6.0 on 2026-01-27 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0020_complaintsettings_daily_limit_changes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsettings',
            name='last_frozen_date',
            field=models.DateField(blank=True, help_text='Date when system was last frozen', null=True),
        ),
    ]
