# Generated by Django 6.0 on 2026-01-27 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0021_complaintsettings_last_frozen_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaintsettings',
            name='auto_unfreeze_time',
            field=models.TimeField(default='00:00', help_text='Daily time when the system automatically unfreezes'),
        ),
    ]
