# Generated by Django 4.2.27 on 2026-03-01 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0022_complaintsettings_auto_unfreeze_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='has_student_reply',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='anonymoussession',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='severity',
            field=models.IntegerField(choices=[(1, '⚪ Low'), (2, '🟢 Medium'), (3, '🟡 High'), (4, '🔴 Urgent')], default=2),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('pending', '🟡 Sent'), ('reviewing', '🔵 Fixing'), ('resolved', '✅ Fixed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='complaintaction',
            name='action_type',
            field=models.CharField(choices=[('submitted', 'Complaint Submitted'), ('read', 'Complaint Read'), ('status_changed', 'Status Changed'), ('assigned', 'Assigned to Staff'), ('escalated', 'Escalated'), ('commented', 'Comment Added'), ('evidence_added', 'Evidence Added'), ('reply', 'Principal Reply'), ('student_reply', 'Student Reply'), ('update_deadline', 'Deadline Updated')], max_length=50),
        ),
        migrations.AlterField(
            model_name='complaintaction',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaintcategory',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaintevidence',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='complaintsettings',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
