# Generated by Django 6.0 on 2026-01-05 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loginhistory',
            name='email',
            field=models.CharField(max_length=255),
        ),
    ]
