# Generated by Django 6.0 on 2026-01-06 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_user_core_user_email_c0c03f_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='preferences',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='user',
            name='style',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
