# Generated by Django 6.0 on 2026-01-06 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_preferences_user_style'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_principal',
            field=models.BooleanField(default=False),
        ),
    ]
