# Generated by Django 6.0 on 2026-01-06 13:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_announcement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and symbols (!@+#$%^&*()) only.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[\\w.@+#!$%^&*()\\-\\[\\]{}|;:\\\'",.<>?/`~]+$', 'Enter a valid username.')]),
        ),
    ]
