# Generated by Django 6.0 on 2026-01-06 13:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Digits and symbols (!@+#$%^&*()) only. Strictly no letters.', max_length=150, unique=True, validators=[django.core.validators.RegexValidator('^[0-9.@+#!$%^&*()\\-\\[\\]{}|;:\\\'",.<>?/`~]+$', 'Enter a valid username (numbers and symbols only, no letters).')]),
        ),
    ]
