# Generated by Django 6.0 on 2026-01-07 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0009_user_registration_ip'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['registration_ip'], name='core_user_registr_45859e_idx'),
        ),
    ]
