# Generated by Django 6.0 on 2026-01-07 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0010_user_core_user_registr_45859e_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeletedIPLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField(db_index=True)),
                ('device_fingerprint', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('deleted_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-deleted_at'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='device_fingerprint',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['device_fingerprint'], name='core_user_device__19e827_idx'),
        ),
        migrations.AddIndex(
            model_name='deletediplock',
            index=models.Index(fields=['ip_address', 'deleted_at'], name='core_delete_ip_addr_9c9570_idx'),
        ),
        migrations.AddIndex(
            model_name='deletediplock',
            index=models.Index(fields=['device_fingerprint', 'deleted_at'], name='core_delete_device__a27e54_idx'),
        ),
    ]
