# Generated by Django 6.0 on 2026-01-24 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_deletediplock_user_device_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='is_edited',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='announcement',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
